site_name: libdmmy
site_url: https://libdmmy.github.io
theme:
  name: material
  logo: assets/face.svg
  favicon: assets/face.svg
  palette:
    scheme: slate
    primary: blue grey
    accent: green
  features:
    - navigation.footer
    - navigation.instant
    - content.code.copy

markdown_extensions:
  - admonition

plugins:
  - search
  - mkdocs-simple-hooks:
      hooks:
        on_post_build: "hooks:copy_wellknown"

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/libdmmy
    - icon: fontawesome/brands/github
      link: https://github.com/libdmmy
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@itsdummybot
    - icon: fontawesome/solid/paper-plane
      link: mailto:itsdummybot@gmail.com
